// @generated by protobuf-ts 2.9.4 with parameter long_type_number,server_generic
// @generated from protobuf file "Job.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { JobState } from "./JobState";
import { JobResult } from "./JobResult";
import { JobParam } from "./JobParam";
import { JobInput } from "./JobInput";
/**
 * @generated from protobuf message Job
 */
export interface Job {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: uint32 kind = 14;
     */
    kind: number;
    /**
     * @generated from protobuf field: string runOn = 2;
     */
    runOn: string;
    /**
     * @generated from protobuf field: uint64 expiration = 3;
     */
    expiration: number;
    /**
     * @generated from protobuf field: uint64 timestamp = 4;
     */
    timestamp: number;
    /**
     * @generated from protobuf field: repeated JobInput input = 5;
     */
    input: JobInput[]; // primary input
    /**
     * @generated from protobuf field: repeated JobParam param = 6;
     */
    param: JobParam[]; // additional parameters
    /**
     * @generated from protobuf field: string customerPublicKey = 7;
     */
    customerPublicKey: string;
    /**
     * @generated from protobuf field: string description = 8;
     */
    description: string;
    /**
     * @generated from protobuf field: string provider = 9;
     */
    provider: string;
    /**
     * @generated from protobuf field: repeated string relays = 10;
     */
    relays: string[];
    /**
     * @generated from protobuf field: JobResult result = 12;
     */
    result?: JobResult;
    /**
     * @generated from protobuf field: JobState state = 11;
     */
    state?: JobState;
    /**
     * @generated from protobuf field: uint64 maxExecutionTime = 13;
     */
    maxExecutionTime: number; // enforced by the provider
}
// @generated message type with reflection information, may provide speed optimized methods
class Job$Type extends MessageType<Job> {
    constructor() {
        super("Job", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "kind", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "runOn", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "expiration", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 4, name: "timestamp", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 5, name: "input", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => JobInput },
            { no: 6, name: "param", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => JobParam },
            { no: 7, name: "customerPublicKey", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "provider", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "relays", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "result", kind: "message", T: () => JobResult },
            { no: 11, name: "state", kind: "message", T: () => JobState },
            { no: 13, name: "maxExecutionTime", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ }
        ]);
    }
    create(value?: PartialMessage<Job>): Job {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.kind = 0;
        message.runOn = "";
        message.expiration = 0;
        message.timestamp = 0;
        message.input = [];
        message.param = [];
        message.customerPublicKey = "";
        message.description = "";
        message.provider = "";
        message.relays = [];
        message.maxExecutionTime = 0;
        if (value !== undefined)
            reflectionMergePartial<Job>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Job): Job {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* uint32 kind */ 14:
                    message.kind = reader.uint32();
                    break;
                case /* string runOn */ 2:
                    message.runOn = reader.string();
                    break;
                case /* uint64 expiration */ 3:
                    message.expiration = reader.uint64().toNumber();
                    break;
                case /* uint64 timestamp */ 4:
                    message.timestamp = reader.uint64().toNumber();
                    break;
                case /* repeated JobInput input */ 5:
                    message.input.push(JobInput.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated JobParam param */ 6:
                    message.param.push(JobParam.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string customerPublicKey */ 7:
                    message.customerPublicKey = reader.string();
                    break;
                case /* string description */ 8:
                    message.description = reader.string();
                    break;
                case /* string provider */ 9:
                    message.provider = reader.string();
                    break;
                case /* repeated string relays */ 10:
                    message.relays.push(reader.string());
                    break;
                case /* JobResult result */ 12:
                    message.result = JobResult.internalBinaryRead(reader, reader.uint32(), options, message.result);
                    break;
                case /* JobState state */ 11:
                    message.state = JobState.internalBinaryRead(reader, reader.uint32(), options, message.state);
                    break;
                case /* uint64 maxExecutionTime */ 13:
                    message.maxExecutionTime = reader.uint64().toNumber();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Job, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* uint32 kind = 14; */
        if (message.kind !== 0)
            writer.tag(14, WireType.Varint).uint32(message.kind);
        /* string runOn = 2; */
        if (message.runOn !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.runOn);
        /* uint64 expiration = 3; */
        if (message.expiration !== 0)
            writer.tag(3, WireType.Varint).uint64(message.expiration);
        /* uint64 timestamp = 4; */
        if (message.timestamp !== 0)
            writer.tag(4, WireType.Varint).uint64(message.timestamp);
        /* repeated JobInput input = 5; */
        for (let i = 0; i < message.input.length; i++)
            JobInput.internalBinaryWrite(message.input[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* repeated JobParam param = 6; */
        for (let i = 0; i < message.param.length; i++)
            JobParam.internalBinaryWrite(message.param[i], writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* string customerPublicKey = 7; */
        if (message.customerPublicKey !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.customerPublicKey);
        /* string description = 8; */
        if (message.description !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.description);
        /* string provider = 9; */
        if (message.provider !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.provider);
        /* repeated string relays = 10; */
        for (let i = 0; i < message.relays.length; i++)
            writer.tag(10, WireType.LengthDelimited).string(message.relays[i]);
        /* JobResult result = 12; */
        if (message.result)
            JobResult.internalBinaryWrite(message.result, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* JobState state = 11; */
        if (message.state)
            JobState.internalBinaryWrite(message.state, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* uint64 maxExecutionTime = 13; */
        if (message.maxExecutionTime !== 0)
            writer.tag(13, WireType.Varint).uint64(message.maxExecutionTime);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Job
 */
export const Job = new Job$Type();
