// @generated by protobuf-ts 2.9.4 with parameter long_type_number,server_generic
// @generated from protobuf file "JobStatus.proto" (syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum JobStatus
 */
export enum JobStatus {
    /**
     * @generated from protobuf enum value: PENDING = 0;
     */
    PENDING = 0,
    /**
     * @generated from protobuf enum value: PROCESSING = 1;
     */
    PROCESSING = 1,
    /**
     * @generated from protobuf enum value: ERROR = 2;
     */
    ERROR = 2,
    /**
     * @generated from protobuf enum value: SUCCESS = 3;
     */
    SUCCESS = 3,
    /**
     * @generated from protobuf enum value: PARTIAL = 4;
     */
    PARTIAL = 4,
    /**
     * @generated from protobuf enum value: PAYMENT_REQUIRED = 7;
     */
    PAYMENT_REQUIRED = 7,
    /**
     * @generated from protobuf enum value: UNKNOWN = 99;
     */
    UNKNOWN = 99
}
